Lecture 04 (gua / Alex Gu)
mit-han-lab/6s965-fall2022 pull request #15
Opened 2022-09-30 21:59 UTC by minimario

2022-10-04 18:14 UTC, zhijian-liu approved these changes
Thanks for your contribution! Please fix these minor formatting issues.

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +### M:N Sparsity [[Mishra, et al. 2021]](https://arxiv.org/pdf/2104.08378.pdf)
```suggestion
### M:N Sparsity [[Mishra et al., 2021]](https://arxiv.org/pdf/2104.08378.pdf)
```

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +M:N sparsity means that out of every $N$ consecutive weights, $M$ are nonzero. A common case is 2;4 sparsity, shown below. Instead of storing each value, we just need to store the nonzero data values
```suggestion
M:N sparsity means that out of every $N$ consecutive weights, at most $M$ are nonzero. A common case is 2:4 sparsity, shown below. Instead of storing each value, we just need to store the nonzero data values, as well as 2-bit indices representing which 2 elements in each consecutive block of 4 are nonzero.
```

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +### Accelerating Recurrent Neural Networks [[Han, et al. 2017]](https://arxiv.org/pdf/1612.00694.pdf)
```suggestion
### Accelerating Recurrent Neural Networks [[Han et al., 2017]](https://arxiv.org/pdf/1612.00694.pdf)
```

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +### EIE: Efficient Inference Engine [[Han, et al. 2016]](https://arxiv.org/pdf/1602.01528.pdf)
```suggestion
### EIE: Efficient Inference Engine [[Han et al., 2016]](https://arxiv.org/pdf/1602.01528.pdf)
```

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +**Architecture**
```suggestion
**Architecture**:
```

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +The EIE architecture is shown below:
```suggestion
The EIE architecture is shown below.
```

2022-10-04 18:14 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +## Section 3: The Lottery Ticket Hypothesis [[Frankle et al. 2019]](https://arxiv.org/pdf/1803.03635.pdf)
```suggestion
## Section 3: The Lottery Ticket Hypothesis [[Frankle et al., 2019]](https://arxiv.org/pdf/1803.03635.pdf)
```

2022-10-04 18:27 UTC, zhijian-liu commented
@minimario, please also upload all figures here.

2022-10-04 19:30 UTC, zhijian-liu requested changes
Please also upload all figures here in this repo. Thanks!

2022-10-11 19:20 UTC, zhijian-liu commented on notes/lecture-04-gua.md
> +| Title       | Introduction to TinyML and Efficient Deep Learning Computing                                                    |
```suggestion
| Title       | Pruning and Sparsity (Part II)                                                    |
```

2022-10-11 19:23 UTC, zhijian-liu commented
@minimario, a friendly reminder: please fix the title and upload all figures in this PR. Thanks!

2022-10-15 13:49 UTC, minimario commented
Hi @zhijian-liu, I fixed the figures now. Thanks!

2022-10-18 13:38 UTC, zhijian-liu approved these changes

2022-10-18 13:39 UTC, merged