Lecture 06 (janicey / Janice Yang)
mit-han-lab/6s965-fall2022 pull request #16
Opened 2022-10-01 21:53 UTC by janicey27

2022-10-04 19:20 UTC, zhijian-liu reviewed
Thanks for your contribution! The scribe looks great. Please
* Fix the minor issues listed below.
* Remove all `.DS_Store` files.

2022-10-04 19:20 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +- However, not all hardware supports this, and there might be unnecessary overhead. These days, per channel quantization is quite popular in real life applications.
```suggestion
However, not all hardware supports this, and there might be unnecessary overhead. These days, per-channel quantization is quite popular in real-life applications. 
```

2022-10-04 19:20 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +- Solution: we can use per channel quantization
```suggestion
- Solution: we can use per-channel quantization
```

2022-10-04 19:20 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +The figure above comes from [[Markus et al., ICCV 2019]](https://hanlab.mit.edu/files/course/slides/MIT-TinyML-Lec06-Quantization-II.pdf), demonstrating how different output channel weights can be, a
```suggestion

The figure above comes from [[Markus et al., ICCV 2019]](https://hanlab.mit.edu/files/course/slides/MIT-TinyML-Lec06-Quantization-II.pdf), demonstrating how different output channel weights can be and how they could be equalized.
```

2022-10-04 19:46 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +    - this becomes harder to impelement as it requires the hardware to generate random bits when quantizing
```suggestion
    - this becomes harder to implement as it requires the hardware to generate random bits when quantizing
```

2022-10-04 19:48 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$ = E[Q(W)x] - \epsilon E[x]$
Please double-check this formula

2022-10-04 19:49 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +The figure above comes from [[Szymon Migacz, 2017]](https://on-demand.gputechconf.com/gtc/2017/presentation/s7310-8-bit-inference-with-tensorrt.pdf), showing an example of clipping weights on certain
```suggestion
The figure above comes from [[Szymon Migacz, 2017]](https://on-demand.gputechconf.com/gtc/2017/presentation/s7310-8-bit-inference-with-tensorrt.pdf), showing an example of clipping weights on a certain layer of ResNet-152, after finding the optimal clipping point using KL Divergence optimization.
```

2022-10-05 19:50 UTC, janicey27 commented on notes/lecture-06-janicey.md
> +$ = E[Q(W)x] - \epsilon E[x]$
This looks the same as the equations on the slides. Could you let me know which part you wanted me to change?

2022-10-11 17:52 UTC, zhijian-liu requested changes
The `.DS_Store` files are still there. Please remove them. Thanks!

2022-10-11 19:25 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +- Intuition, $1*100 = 10*10$, so taking product of the two numbers then the square root should give you the same product, you just get two equalized input numbers now.
```suggestion
- Intuition, $1 * 100 = 10 * 10$, so taking the product of the two numbers, then the square root should give you the same product, and you just get two equalized input numbers now. 
```

2022-10-11 19:26 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$ = f(W^{(i+1)}*f(W^{(i)}x^{(i)} + b^{(i)}) + b^{(i+1)})$
```suggestion
$ = f(W^{(i+1)} * f(W^{(i)}x^{(i)} + b^{(i)}) + b^{(i+1)})$
```

2022-10-11 19:26 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$ = f(W^{(i+1)}S*f(S^{-1}W^{(i)}x^{(i)} + S^{-1}b^{(i)}) + b^{(i+1)})$
```suggestion
$ = f(W^{(i+1)}S * f(S^{-1}W^{(i)}x^{(i)} + S^{-1}b^{(i)}) + b^{(i+1)})$
```

2022-10-11 19:26 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +To make weight ranges of different output channels match as closely as possible, we choose $s_j$ where $s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{(r^{(i)}_{oc=j}*r^{(i+1)}_{ic=j})}$, where $r^{(i)}_{oc=
```suggestion
To make weight ranges of different output channels match as closely as possible, we choose $s_j$ where $s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{(r^{(i)}_{oc=j} * r^{(i+1)}_{ic=j})}$, where $r^{(i)}_{oc=j}$ is the weight range of output channel $j$ in Layer $i$, and $r^{(i+1)}_{ic=j}$ is the weight range of input channel $j$ in layer $i+1$. 
```

2022-10-11 19:30 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +To make weight ranges of different output channels match as closely as possible, we choose $s_j$ where $s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{(r^{(i)}_{oc=j} * r^{(i+1)}_{ic=j})}$, where $r^{(i)}_{o
```suggestion
To make weight ranges of different output channels match as closely as possible, we choose $s_j$ where $s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{(r^{(i)}_{oc=j} \cdot r^{(i+1)}_{ic=j})}$, where $r^{(i)}_{oc=j}$ is the weight range of output channel $j$ in Layer $i$, and $r^{(i+1)}_{ic=j}$ is the weight range of input channel $j$ in layer $i+1$. 
```

2022-10-11 19:34 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +To make weight ranges of different output channels match as closely as possible, we choose $s_j$ where $s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{(r^{(i)}_{oc=j} \cdot r^{(i+1)}_{ic=j})}$, where $r^{(i)
```suggestion
To make the weight ranges of different output channels match as closely as possible, we choose $s_j$ where
$$s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{r^{(i)}_{oc=j} \cdot r^{(i+1)}_{ic=j}},$$
where $r^{(i)}_{oc=j}$ is the weight range of output channel $j$ in Layer $i$, and $r^{(i+1)}_{ic=j}$ is the weight range of input channel $j$ in layer $i+1$. 
```

2022-10-11 19:35 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$$s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{r^{(i)}_{oc=j} \cdot r^{(i+1)}_{ic=j}},$$
```suggestion
$$s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{r^{(i)}_{oc=j} \cdot r^{(i+1)}_{ic=j}},$$

```

2022-10-11 19:35 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +To make the weight ranges of different output channels match as closely as possible, we choose $s_j$ where
```suggestion
To make the weight ranges of different output channels match as closely as possible, we choose $s_j$ where

```

2022-10-11 19:39 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$$s_j = \frac{1}{r^{(i+1)}_{ic=j}} \sqrt{r^{(i)}_{oc=j} \cdot r^{(i+1)}_{ic=j}},$$
```suggestion
$$s_j = \frac{1}{r_{ic=j}^{(i+1)}} \sqrt{r_{oc=j}^{(i)} \cdot r_{ic=j}^{(i+1)}},$$
```

2022-10-11 19:39 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +where $r^{(i)}_{oc=j}$ is the weight range of output channel $j$ in Layer $i$, and $r^{(i+1)}_{ic=j}$ is the weight range of input channel $j$ in layer $i+1$.
```suggestion
where $r_{oc=j}^{(i)}$ is the weight range of output channel $j$ in Layer $i$, and $r_{ic=j}^{(i+1)}$ is the weight range of input channel $j$ in layer $i+1$. 
```

2022-10-11 19:41 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$D_{KL}(P||Q) = \sum^{N}_{i}P(x_i)log\frac{P(x_i)}{Q(x_i)}$
```suggestion
$D_{KL}(P||Q) = \sum_{i}^{N}P(x_i)log\frac{P(x_i)}{Q(x_i)}$
```

2022-10-11 19:42 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$ = E[Q(W)x] - \epsilon E[x]$
```suggestion
$$E[y] = E[Wx] + E[\epsilon x] - E[\epsilon x] = E[Q(W)x] - \epsilon E[x],$$
```

2022-10-11 19:43 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$ = f(W^{(i+1)}S * f(S^{-1}W^{(i)}x^{(i)} + S^{-1}b^{(i)}) + b^{(i+1)})$
```suggestion
$$y^{(i+1)} = f(W^{(i+1)}x^{(i+1)} + b^{(i+1)}) = f(W^{(i+1)} * f(W^{(i)}x^{(i)} + b^{(i)}) + b^{(i+1)}) = f(W^{(i+1)}S * f(S^{-1}W^{(i)}x^{(i)} + S^{-1}b^{(i)}) + b^{(i+1)})$$
```

2022-10-11 19:44 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +where $S = diag(s)$, $s_j$ is the weight equalization scale factor of output channel $j$. $f$ has to be linear.
```suggestion
where $S = \text{diag}(s)$ and $s_j$ is the weight equalization scale factor of output channel $j$. Here, $f$ has to be linear. 
```

2022-10-11 19:45 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$argmin_v || Wx - \lfloor\lfloor W \rfloor + h(V)\rceil x ||^2_F + \lambda f_{reg}(V)$
```suggestion
- Optimize the difference between the original $Wx$ and the reconstructed $\lfloor\lfloor W \rfloor + h(V)\rceil x$:

$$\text{argmin}_v || Wx - \lfloor\lfloor W \rfloor + h(V)\rceil x ||^2_F + \lambda f_{reg}(V)$$
```

2022-10-11 19:46 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$D_{KL}(P||Q) = \sum_{i}^{N}P(x_i)log\frac{P(x_i)}{Q(x_i)}$
```suggestion
$$D_{KL}(P||Q) = \sum_{i}^{N}P(x_i)log\frac{P(x_i)}{Q(x_i)}$$
```

2022-10-11 19:47 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$$\text{argmin}_v || Wx - \lfloor\lfloor W \rfloor + h(V)\rceil x ||^2_F + \lambda f_{reg}(V)$$
```suggestion
$$\arg\min_v || Wx - \lfloor\lfloor W \rfloor + h(V)\rceil x ||^2_F + \lambda f_{reg}(V)$$
```

2022-10-11 19:48 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +- We try to learn a parameter $delta$ between [0, 1] that optimizes rounding for each weight.
```suggestion
- We try to learn a parameter $\Delta$ between [0, 1] that optimizes rounding for each weight. 
```

2022-10-11 19:49 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +- Weights are quantized to +1, -1, and 0, using $delta = 0.7 * E(r)$ as a threshold to map out 3 distinct regions: $r > \Delta$, $|r| \leq \Delta$, and $r < -\Delta$.
```suggestion
- Weights are quantized to +1, -1, and 0, using $\Delta = 0.7 * E(r)$ as a threshold to map out 3 distinct regions: $r > \Delta$, $|r| \leq \Delta$, and $r < -\Delta$. 
```

2022-10-11 19:52 UTC, zhijian-liu commented on notes/lecture-06-janicey.md
> +$$D_{KL}(P||Q) = \sum_{i}^{N}P(x_i)log\frac{P(x_i)}{Q(x_i)}$$
```suggestion
$$D_{KL}(P||Q) = \sum_{i}^{N}P(x_i)\log\frac{P(x_i)}{Q(x_i)}$$
```

2022-10-11 19:53 UTC, zhijian-liu commented
I have made the edits. Thanks again for your contribution!

2022-10-11 19:54 UTC, merged