Lecture 06 (emontas / Enrique Montas)
mit-han-lab/6s965-fall2022 pull request #17
Opened 2022-10-04 00:33 UTC by enriquemontas

2022-10-04 19:22 UTC, zhijian-liu reviewed
Thanks for your contribution! The scribe looks great. Please
* Fix the issues commented below.
* Remove all `.DS_Store` files.

Please re-request the review when ready. Thanks!

2022-10-04 19:53 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +**Terinary Weight Networks:** [[Li et al., Arxiv 2016]](https://arxiv.org/abs/1605.04711) Weights $$\in [-1, 0, 1]$$
```suggestion
**Ternary Weight Networks:** [[Li et al., Arxiv 2016]](https://arxiv.org/abs/1605.04711) Weights $$\in [-1, 0, 1]$$

```

2022-10-04 19:54 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +**Trained Terinary Quantization:** [[Zhu et al., ICLR 2017]](https://arxiv.org/abs/1612.01064) Instead of using a fixed $$r_t$$, introduce two trainable parameters $$w_p, w_n$$ to represent the negat
```suggestion
**Trained Ternary Quantization:** [[Zhu et al., ICLR 2017]](https://arxiv.org/abs/1612.01064) Instead of using a fixed $$r_t$$, introduce two trainable parameters $$w_p, w_n$$ to represent the negative and positive scales.

```

2022-10-04 19:54 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +Mixed-Precision Quantization: Layers can have uneven widths of weights and activations in the quantized model.
```suggestion
Uniform Quantization: Layers have uniform widths of weights and activations in the quantized model.

Mixed-Precision Quantization: Layers can have uneven widths of weights and activations in the quantized model.

```

2022-10-11 17:51 UTC, zhijian-liu requested changes
The `.DS_Store` files are still there. Please remove them. Thanks!

2022-10-11 19:16 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +-- outlier weight values that cause precision loss of other wieghts after quantization
```suggestion
-- outlier weight values that cause precision loss of other weights after quantization

```

2022-10-11 19:16 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +- scaling down layer *i* wieghts $$W^{(i)}_{oc=a}$$ of output channel *oc=a* by *s*
```suggestion
- scaling down layer *i* weights $$W^{(i)}_{oc=a}$$ of output channel *oc=a* by *s*

```

2022-10-11 19:16 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +- scaling up layer *i+1* wieghts $$W^{(i+1)}_{ic=a}$$ of input channel *ic=a* by *s*
```suggestion
- scaling up layer *i+1* weights $$W^{(i+1)}_{ic=a}$$ of input channel *ic=a* by *s*

```

2022-10-11 19:17 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +##### Rescaling to equalize the weigth ranges of different channels
```suggestion
##### Rescaling to equalize the weight ranges of different channels

```

2022-10-11 19:17 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +-- Per-Channel Weigth Quantization will outperform Per-Tensor Weight Quantization
```suggestion
-- Per-Channel Weight Quantization will outperform Per-Tensor Weight Quantization

```

2022-10-11 19:17 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +To make weigth ranges of different output channels match as closely as possible,
```suggestion
To make weight ranges of different output channels match as closely as possible,

```

2022-10-11 19:17 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +##### Adaptive Rounding for Weigth Quantization
```suggestion
##### Adaptive Rounding for Weight Quantization

```

2022-10-11 19:57 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +where $$r_{oc=j}^{(i)}$$ is the weight range of *output* channel *j* in Layer *i*, and $$r_{ic=j}^{(2)}$$ is the weight range of *input* channel *j* in Layer $$i+1$$
```suggestion
where $r_{oc=j}^{(i)}$ is the weight range of *output* channel *j* in layer *i*, and $r_{ic=j}^{(i + 1)}$ is the weight range of *input* channel *j* in layer $i+1$

```

2022-10-11 19:58 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +- short term tuning required, (almost) post-training quantization
```suggestion
*Philosophy:* Weights are correlated with each other. Thus rounding each weight (to the nearest) is suboptimal for rounding the entire tensor. [[Nagel et al., PMLR 2020]](https://arxiv.org/abs/2004.10568)

What is optimal? Rounding that reconstructs the original *activation* the best, which may be very different.
- only for weight quantization
- short term tuning required, (almost) post-training quantization
```

2022-10-11 20:00 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$f_{reg}(\mathbf{V})$$ is regularization that encourages **h(V)** to be binary
```suggestion
- instead of $\lfloor w\rceil$, we want to choose from $\{\lfloor w\rfloor, \lceil w\rceil\}$ to get the best reconstruction.
- we can take a learning-based method to find quantized value $\widetilde{w} = \lfloor \lfloor w\rfloor+\delta\rceil, \delta\in [0,1]$ where

$$\arg\min_v||Wx-\widetilde Wx||^2_F + \lambda f_{reg}(V)$$
$$\rightarrow\text{argmin}_\mathbf{v}||\mathbf{Wx}-\lfloor\lfloor\mathbf{W}\rfloor + \mathbf{h}(\mathbf{V})\rceil\mathbf{x}||^2_F + \lambda f_{reg}(\mathbf{V})$$
**x** is the input to the layer, **V** is a random variable of the same shape
**h**() is a function to map the range to $$(0,1)$$, ie rectified sigmoid
$$f_{reg}(\mathbf{V})$$ is regularization that encourages **h(V)** to be binary

```

2022-10-11 20:02 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$\rightarrow\text{argmin}_\mathbf{v}||\mathbf{Wx}-\lfloor\lfloor\mathbf{W}\rfloor + \mathbf{h}(\mathbf{V})\rceil\mathbf{x}||^2_F + \lambda f_{reg}(\mathbf{V})$$
```suggestion
- we can take a learning-based method to find quantized value $\widetilde{w} = \lfloor \lfloor w\rfloor+\delta\rceil, \delta\in [0,1]$:

$$\arg\min_v||Wx-\widetilde Wx||^2_F + \lambda f_{reg}(V) \rightarrow \arg\min_v||Wx-\lfloor\lfloor{W}\rfloor + {h}({V})\rceil{x}||^2_F + \lambda f_{reg}({V})$$

```

2022-10-11 20:03 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$f_{reg}(\mathbf{V})$$ is regularization that encourages **h(V)** to be binary
```suggestion
Here, **x** is the input to the layer, **V** is a random variable of the same shape, **h**() is a function to map the range to $(0,1)$, ie rectified sigmoid, and $f_{reg}(\mathbf{V})$ is regularization that encourages **h(V)** to be binary

```

2022-10-11 20:04 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +- $$|r|_{max} = |\mathbf{W}|_{max}$$
```suggestion
- $$|r|_{max} = |{W}|_{max}$$

```

2022-10-11 20:05 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$\hat{r}^{(t)}_{\min, \max} = \alpha\cdot r^{(t)}_{\min, \max}+(1-\alpha)\cdot\hat{r}^{(t-1)}_{\min, \max}$$
```suggestion
$$\hat{r}_{\min, \max}^{(t)} = \alpha\cdot r_{\min, \max}^{(t)}+(1-\alpha)\cdot\hat{r}_{\min, \max}^{(t-1)}$$

```

2022-10-11 20:05 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$\min_{|r|_{max}}\mathbb{E}[(\mathbf{X}-Q(\mathbf{X}))^2]$$
```suggestion
$$\min_{|r|_{max}}\mathbb{E}[({X}-Q({X}))^2]$$

```

2022-10-11 20:05 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +-- *minimize the mean-square-error* between inputs **X** and reconstructed quantized inputs $$Q(\mathbf{X})$$
```suggestion
-- *minimize the mean-square-error* between inputs **X** and reconstructed quantized inputs $Q({X})$

```

2022-10-11 20:06 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +-- assume inpits are in in Gaussian or Laplace distribution.
```suggestion
-- assume inputs are in Gaussian or Laplace distribution.
```

2022-10-11 20:08 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +|$$\mathbb{B}$$| $$\mathbb{B}$$ |xnor, popcount | ~$$32\times$$ less | ~$$58\times$$ less |
```suggestion
| input | weight | operations | memory | computation |
|---|---|---|---|---|
|$\mathbb{R}$| $\mathbb{R}$ |+ $\times$| $1\times$ | $1\times$ |
|$\mathbb{R}$| $\mathbb{B}$ |+ -| ~$32\times$ less | ~$2\times$ less |
|$\mathbb{B}$| $\mathbb{B}$ |xnor, popcount | ~$32\times$ less | ~$58\times$ less |

```

2022-10-11 20:09 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +
```suggestion
**Trained Ternary Quantization:** [[Zhu et al., ICLR 2017]](https://arxiv.org/abs/1612.01064) Instead of using a fixed $r_t$, introduce two trainable parameters $w_p, w_n$ to represent the negative and positive scales.


```

2022-10-11 20:09 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +**Ternary Weight Networks:** [[Li et al., Arxiv 2016]](https://arxiv.org/abs/1605.04711) Weights $$\in [-1, 0, 1]$$
```suggestion
**Ternary Weight Networks:** [[Li et al., Arxiv 2016]](https://arxiv.org/abs/1605.04711) Weights $\in [-1, 0, 1]$

```

2022-10-11 20:10 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +|$\mathbb{B}$| $\mathbb{B}$ |xnor, popcount | ~$32\times$ less | ~$58\times$ less |
```suggestion
|$\mathbb{R}$| $\mathbb{R}$ |+ x| 1x | 1x |
|$\mathbb{R}$| $\mathbb{B}$ |+ -| ~32x less | ~2x less |
|$\mathbb{B}$| $\mathbb{B}$ |xnor, popcount | ~32x less | ~58x less |

```

2022-10-11 20:11 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$\mathbb{E}[x]$$ can be inferred from batch normalization
```suggestion
where the $- \epsilon\mathbb{E}[x]$ term is absorbed into the bias parameter
$\mathbb{E}[x]$ can be inferred from batch normalization

```

2022-10-11 20:12 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$D_{KL}(P||Q)=\sum^N_i P(x_i)\log\frac{P(x_i)}{Q(x_i)}$$
```suggestion
$$D_{KL}(P||Q)=\sum_i^N P(x_i)\log\frac{P(x_i)}{Q(x_i)}$$

```

2022-10-11 20:13 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +$$D_{KL}(P||Q)=\sum_i^N P(x_i)\log\frac{P(x_i)}{Q(x_i)}$$
```suggestion

$$D_{KL}(P||Q)=\sum_i^N P(x_i)\log\frac{P(x_i)}{Q(x_i)}$$

```

2022-10-11 20:16 UTC, zhijian-liu commented on notes/lecture-06-emontas.md
> +*intuition: KL divergence measures the information lost when approximating a given encoding*
```suggestion
-- spend dynamic range on outliers hurts representation ability
-- use *mean* of the min/max of each sample in the batches
-- *minimize the mean-square-error* between inputs **X** and reconstructed quantized inputs $Q({X})$
$$\min_{|r|_{max}}\mathbb{E}[({X}-Q({X}))^2]$$

-- assume inputs are in Gaussian or Laplace distribution.
 in a Laplace distribution (0, *b*) optimal clipping values can be numerically computed as $$|r|_{\max} = 2.83b, 3.98b, 5.03b$$ for 2, 3, 4 bits.
-- the Laplace parameter *b* can be estimated from calibration input distribution.
-- *minimize loss of information* since integer models encode the same information as the original floating-point model,
we can measure information loss with Kullback-Leibler divergence (relative information divergence):
-- for two discrete probability distributions *P, Q*

$$D_{KL}(P||Q)=\sum_i^N P(x_i)\log\frac{P(x_i)}{Q(x_i)}$$

*intuition: KL divergence measures the information lost when approximating a given encoding*

```

2022-10-11 20:18 UTC, zhijian-liu commented
I have made the edits. Thanks again for your contribution.

2022-10-11 20:19 UTC, merged

2022-10-13 21:07 UTC, enriquemontas commented
awesome, I was about to ask how to remove the .DS files during office hours today. I'll be sure to not add them on my next scribe duty.