Create lecture-08-dansl.md
mit-han-lab/6s965-fall2022 pull request #20
Opened 2022-10-04 22:04 UTC by btsp6

I tried my best but the latter part of the lecture is a little too hardware technical for me to grok :( I will accept any point penalties.

2022-10-11 17:20 UTC, zhijian-liu requested changes
Thanks for your contribution! The scribe looks great. Please
* Add the note information section as in https://github.com/mit-han-lab/6s965-fall2022/blob/main/notes/lecture-01-johndoe.md
* Address the comments below.

Please re-request the review when you find this PR ready. Btw, feel free to come to the office hour. We would be happy to explain more about the hardware part.

2022-10-11 17:20 UTC, zhijian-liu commented on notes/lecture-08-dansl.md
> +If we want to create a sub-network with a smaller kernel size, depth, or channel width, we can use progressive pruning. We can reduce
This sentence is not complete.

2022-10-18 13:55 UTC, zhijian-liu commented
@btsp6, please let us know when the scribe is ready for another round of review.

2022-10-25 17:45 UTC, btsp6 commented
Sorry for the delay, I've updated the requested changes.

2022-10-25 17:49 UTC, zhijian-liu approved these changes

2022-10-25 17:50 UTC, merged