Create lecture-02-xgx.md
mit-han-lab/6s965-fall2022 pull request #8
Opened 2022-09-20 21:53 UTC by Guangxuan-Xiao

2022-09-21 22:01 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +| Input Features $X$  | $ (n, c_i, w_i)$   | $(n, c_i, h_i, w_i)$   |
Same here.

2022-09-21 22:01 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +  $h_0 + h_i + 2p-k_h + 1$
`$h_0 + h_i + 2p-k_h + 1$` -> $h_o = h_i + 2p-k_h + 1$

2022-09-21 22:04 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Data movement - > more memory reference -> more energys
`- >` -> `->`

2022-09-22 00:23 UTC, Guangxuan-Xiao commented
Thank you very much for pointing them out! I resolved them. Please have a look.

2022-09-24 20:55 UTC, zhijian-liu requested changes
Thanks for the contribution! Please fix these formatting issues. Also, the text in the current version is fragmented. Please complete them as sentences.

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +$h_o = h_i - k_h + 1$
Please wrap it into the previous line.

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Three Dimensions: Storage, Latency, and Energy
Please complete them as sentences.

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### Strided Convulution Layer
```suggestion
#### Strided convolution layer
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Strided Convulution Layers increase the receptive field without increasing the layer.
```suggestion
Strided convolution layers increase the receptive field without increasing the layer.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Normalizing the features makes training faster
```suggestion
Normalizing the features makes the model optimization faster.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Quantization friendly: ReLU
```suggestion
- ReLU is efficient, and quantization-friendly, but has zero gradients for negative inputs.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- GeLU, Swish, hard swish: hard to quantize
```suggestion
- GeLU, Swish, and Hardswish are more effective but hard to be quantized.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Neurons  = Features = Activations: Input / intermediate / Output values in neural nets.
```suggestion
Neurons  = Features = Activations: Input / intermediate / output values in neural nets.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +$c_o$: Output Channels
```suggestion
$y_i = \sum_j w_{ij}x_j+b_i$, where $n$ is the batch size, $c_i$ is the number of input channels, and $c_o$ is the number of output channels.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +| bias $b$            | $(c_o, )$    |
```suggestion
| Bias $b$            | $(c_o, )$    |
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +The output neuron is connected to input neurons in the receptive field.
```suggestion
The output neuron is only connected to input neurons in the receptive field.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +| bias $b$            | $(c_o, )$          | $(c_o, )$              |
```suggestion
| Bias $b$            | $(c_o, )$          | $(c_o, )$              |
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +  $h_o + h_i + 2p-k_h + 1$
```suggestion
  $h_o = h_i + 2p-k_h + 1$
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- In convolution , each output elelment depends on $k_h \times k_w$  in the input.
```suggestion
- In convolution, each output element depends on $k_h \times k_w$ in the input.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Each successive convulution adds $k-1$ to the receptive field size.
```suggestion
- Each successive convolution adds $k-1$ to the receptive field size.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Downsample the feature map to a smaller size, and graduallyreduceg the size of the feature maps.
```suggestion
Pooling layers are used to downsample the feature map and gradually reduce the size of feature maps.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Attention: finding the relationship between each token, problem $O(n^2)$ complexity and when $n$ is very large it will be very slow.
```suggestion
Transformer is composed of multiple self-attention layers, which find the relationship between tokens. The computational complexity of self-attention is $O(n^2)$, where $n$ is the token size. Therefore, it will be very slow with large token size.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +### Fully-connected layer (Linear layer)
```suggestion
### Fully-connected layer (linear layer)
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Other: Reflection Padding, replication padding, constant padding.
```suggestion
- Other: reflection padding, replication padding, constant padding.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +| Description | Reviewing the basics of deep learning and introducing efficiency metrics for neural networks. |
```suggestion
| Title       | Basics of Neural Networks                                                                |
| ----------- | ---------------------------------------------------------------------------------------- |
| Lecturer    | Song Han                                                                                 |
| Date        | 09/13/2022                                                                               |
| Note Author | Guangxuan Xiao (xgx)                                                                     |
| Description | Review the basics of deep learning and introduce efficiency metrics for neural networks. |
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +## Terminology of Neural Networks
```suggestion
## Terminology of neural networks
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +## Popular Neural Network Layers
```suggestion
## Popular neural network layers
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +### Convolution Layer
```suggestion
### Convolution layer
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### Group Convolution Layer
```suggestion
#### Group convolution layer
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +### Normalization Layer
```suggestion
### Normalization layer
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +## Efficiency metrics for Deep learning
```suggestion
## Efficiency metrics for deep learning
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +## Popular CNN Architectures
```suggestion
## Popular CNN architectures
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### Number of Parameters
```suggestion
#### Number of parameters
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### Total / Peak activation
```suggestion
#### Total and peak activation
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### MACs: Multiply-Accumulate Operations
```suggestion
#### MACs: multiply-accumulate operations
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### FLOP: Floating Point Operation
```suggestion
#### FLOP: floating point operation
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Non-linear functions
```suggestion
Activation functions are usually non-linear.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +DRAM Access > SRAM Access > FP Mult > INT Mult > Register File > FP Add > INT Add
Please complete them as sentences.

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +### Memory related
```suggestion
### Memory-related metrics
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +### Computation related
```suggestion
### Computation-related metrics
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Grouped Convolution: $c_i\times k_w \times k_h \times h_o \times w_o \times c_o / g$
```suggestion
- Grouped convolution: $c_i\times k_w \times k_h \times h_o \times w_o \times c_o / g$
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Depthwise Convolution: $k_w \times k_h \times h_o \times w_o \times c_o$
```suggestion
- Depthwise convolution: $k_w \times k_h \times h_o \times w_o \times c_o$
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- AlexNet have 724MACs
```suggestion
As an example, AlexNet has 724M MACs.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +e.g. AlexNet has 724 MACs, so the total number of floating point operations will be 1.4G FLOPs.
```suggestion
For instance, AlexNet has 724M MACs, so the number of floating point operations will be 1.4G.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- e.g. AlexNet 61M parameters, using fp32 = 244MB, using int8 = 61MB
```suggestion
For example, AlexNet has 61M parameters, so its model size would be 244MB (with FP32) and 61MB (with INT8).
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +Padding can keep the output feature map size the same as the  input feature map size.
```suggestion
Padding keeps the output feature map size the same as the input feature map size.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +#### Receptive Field
```suggestion
#### Receptive field
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +A group of narrower convolutions.
This is not very clear. Please define with more details.

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Transposed Convolution: super-resolution, segmentation, backprop.
```suggestion
- Transposed convolution can be used to upsample the feature map (e.g., in super-resolution and segmentation).
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Dilated Convolution
```suggestion
- Dilated convolution can be used to increase the receptive field with dilated convolution kernels.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- MobileNetV2: depth-wise convolution
```suggestion
- MobileNetV2 introduces depthwise convolution to effectively reduce the computation cost.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- ResNet: introduce a residual connection to allow gradient flow.
```suggestion
- ResNet introduces residual connections to allow better gradient flow.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- AlexNet: the first architecture to adopt an architecture with consecutive convolutional layers (conv layer 3, 4, and 5).
```suggestion
- AlexNet is the first to adopt an architecture with consecutive convolutional layers.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Grouped Convolution: $c_o c_i k_h k_w / g$
```suggestion
- Grouped convolution: $c_o c_i k_h k_w / g$
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Depth-wise convolution: $c_o k_w k_h$
```suggestion
- Depthwise convolution: $c_o k_w k_h$
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- MobileNetV2: depth-wise convolution
Please add citations for these papers.

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +MAC: $a = a+b\times c$
```suggestion
A multiply-accumulate (MAC) operation is $a = a+b\times c$. Here are the number of MACs for common operators:
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- One floating-point MAC = Two FLOPs
```suggestion
One floating-point multiply-accumulate (MAC) operation corresponds to two floating-point operations (FLOP): multiply and add.
```

2022-09-24 20:55 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +- Floating Point Operation Per Second (FLOPS)
```suggestion
- Floating point operation per second (FLOPS)
```

2022-09-30 20:47 UTC, zhijian-liu commented
@Guangxuan-Xiao, could you update the scribe notes according to the comments?

2022-10-01 17:34 UTC, Guangxuan-Xiao reviewed
Revised

2022-10-01 17:34 UTC, Guangxuan-Xiao reviewed
Reviewed

2022-10-01 17:37 UTC, Guangxuan-Xiao reviewed
resolved some outdated suggestions

2022-10-01 17:39 UTC, Guangxuan-Xiao reviewed
Reviewed the change request

2022-10-01 17:41 UTC, Guangxuan-Xiao commented
> Thanks for the contribution! Please fix these formatting issues. Also, the text in the current version is fragmented. Please complete them as sentences.

Thank you very much for the revision and I am sorry for the late reply. Please have a look at this version.

2022-10-04 19:23 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +DRAM Access > SRAM Access > FP Mult > INT Mult > Register File > FP Add > INT Add
This is not resolved.

2022-10-04 19:23 UTC, zhijian-liu commented on notes/lecture-02-xgx.md
> +A group of narrower convolutions.
This is not resolved.

2022-10-04 19:24 UTC, zhijian-liu requested changes
Please resolve these remaining comments.

2022-10-06 02:54 UTC, Guangxuan-Xiao reviewed
Resolved

2022-10-11 19:38 UTC, zhijian-liu commented
@Guangxuan-Xiao, could you please double-check that the content in this PR is up-to-date? Thanks!

2022-10-18 13:58 UTC, zhijian-liu commented
@Guangxuan-Xiao, please polish this scribe and let us know when it's ready for another round of review.

2022-12-14 04:37 UTC, Guangxuan-Xiao reviewed
Resolved

2022-12-14 04:37 UTC, Guangxuan-Xiao commented on notes/lecture-02-xgx.md
> +A group of narrower convolutions.
Resolved

2022-12-14 04:37 UTC, Guangxuan-Xiao commented on notes/lecture-02-xgx.md
> +DRAM Access > SRAM Access > FP Mult > INT Mult > Register File > FP Add > INT Add
Resolved

2022-12-14 16:27 UTC, zhijian-liu approved these changes

2022-12-14 16:27 UTC, merged